# just a simple workflow that clones repo with library and runs build.sh
name: Build
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [armv7-a, armv8-a, x86-android, x86_64-android, x86-linux, x86_64-linux]
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: |
          sudo apt update -y
          sudo apt upgrade -y
          sudo apt install make -y
          sudo apt install automake -y
          sudo apt install autoconf -y
          sudo apt install libtool -y
          sudo apt install build-essential -y
          sudo apt install gcc-multilib -y
          sudo apt install dos2unix -y
          git clone https://github.com/yaml/libyaml
          sudo chmod -R 777 *
          dos2unix build.sh
      - name: Build
        continue-on-error: true
        run: ./build.sh ${{matrix.arch}}
      - name: Log
        continue-on-error: true
        if: true
        run: cd libyaml && cat config.log
      - uses: actions/upload-artifact@v2
        with:
          name: libyaml-${{matrix.arch}}
          path: libyaml/src/.libs/libyaml.a
